### ISSUE TITLE
SpreadsheetWorksheet.clear(callback) throws error on empty sheet

### ISSUE THREAD

**Issue by guido4000** [theoephraim/node-google-spreadsheet#100]
When trying to clear an empty sheet the clear function throws an error. 

```
sheet 1: automation 1x1

events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'setValue' of undefined
    at /Users/main12/Projects/fun/sql/sqlite/testing/node_modules/google-spreadsheet/index.js:397:17
    at /Users/main12/Projects/fun/sql/sqlite/testing/node_modules/google-spreadsheet/index.js:343:7
    at /Users/main12/Projects/fun/sql/sqlite/testing/node_modules/google-spreadsheet/index.js:166:15
    at Parser.<anonymous> (/Users/main12/Projects/fun/sql/sqlite/testing/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:90:13)
    at Parser.emit (events.js:182:7)
    at Object.onclosetag (/Users/main12/Projects/fun/sql/sqlite/testing/node_modules/xml2js/lib/xml2js.js:445:26)
    at emit (/Users/main12/Projects/fun/sql/sqlite/testing/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/Users/main12/Projects/fun/sql/sqlite/testing/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/Users/main12/Projects/fun/sql/sqlite/testing/node_modules/sax/lib/sax.js:905:7)
```

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
