### ISSUE TITLE
options.uri is undefined when calling SpreadsheetRow.save()

### ISSUE THREAD

**Issue by tsolace** [theoephraim/node-google-spreadsheet#118]
```
undefined
/home/white/Programs/Bustarep/main.js:20
          throw err;
          ^

Error: options.uri is a required argument
    at Request.init (/home/white/Programs/Bustarep/node_modules/google-spreadsheet/node_modules/request/request.js:246:31)
    at new Request (/home/white/Programs/Bustarep/node_modules/google-spreadsheet/node_modules/request/request.js:142:8)
    at request (/home/white/Programs/Bustarep/node_modules/google-spreadsheet/node_modules/request/index.js:55:10)
    at async.series.request (/home/white/Programs/Bustarep/node_modules/google-spreadsheet/index.js:147:9)
    at /home/white/Programs/Bustarep/node_modules/google-spreadsheet/node_modules/async/lib/async.js:718:13
    at Immediate.iterate [as _onImmediate] (/home/white/Programs/Bustarep/node_modules/google-spreadsheet/node_modules/async/lib/async.js:262:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by jamiekrcmar** [comment]
i believe you have to add a call back to the save function even though its not specified in the documentation like this       

cell.save(function(err){

          
        });

**Comment by JulioC** [comment]
Looks like the API doesn't return the `edit` link anymore. My sheet is published and enabled for public (non authorized) edits and I'm using it from a G Suite domain.

Related to https://github.com/theoephraim/node-google-spreadsheet/pull/152

**Comment by JulioC** [comment]
I've managed to work around this issue by authenticating with the API, as described on the README.

**Comment by theoephraim** [comment]
FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
