### ISSUE TITLE
InvalidGrant

### ISSUE THREAD

**Issue by glennswest** [theoephraim/node-google-spreadsheet#151]
Seems like no matter what I do, I get invalid grant on trying to build the connection.

dhcp-65-33:cbdp gwest$ node test.js
Set Auth
{ '0': 
   Error: invalid_grant
       at Request._callback (/Users/gwest/cbdp/node_modules/google-spreadsheet/node_modules/google-auth-library/node_modules/gtoken/lib/index.js:215:34)
       at Request.self.callback (/Users/gwest/cbdp/node_modules/google-spreadsheet/node_modules/google-auth-library/node_modules/request/request.js:187:22)
       at emitTwo (events.js:106:13)
       at Request.emit (events.js:191:7)
       at Request.<anonymous> (/Users/gwest/cbdp/node_modules/google-spreadsheet/node_modules/google-auth-library/node_modules/request/request.js:1044:10)
       at emitOne (events.js:96:13)
       at Request.emit (events.js:188:7)
       at IncomingMessage.<anonymous> (/Users/gwest/cbdp/node_modules/google-spreadsheet/node_modules/google-auth-library/node_modules/request/request.js:965:12)
       at emitNone (events.js:91:20)
       at IncomingMessage.emit (events.js:185:7) }
Update Data

-----> test.js
var GoogleSpreadsheet = require('google-spreadsheet');
var util = require('util');

var doc = new GoogleSpreadsheet('1UUpfeHLrl59rYUywu0RPJLTqw1LOW8jX7LLaSbI2VBc');
var sheet;
creds = require('./google-generated-creds.json');

function updatedata(err,token)
{
console.log(util.inspect(arguments));
console.log("Update Data");

}

console.log("Set Auth");
doc.useServiceAccountAuth(creds, updatedata);

**Comment by theoephraim** [comment]
FYI - I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
