### ISSUE TITLE
Error: Uncaught, unspecified "error" event. (null)

### ISSUE THREAD

**Issue by bitliner** [theoephraim/node-google-spreadsheet#153]
`row.update()` causes the following error:

```
Error: Uncaught, unspecified "error" event. (null)
    at Parser.emit (events.js:163:17)
    at Parser.exports.Parser.Parser.parseString (/Users/hellouser/google-spreadsheet/node_modules/xml2js/lib/xml2js.js:512:16)
    at Parser.parseString (/Users/hellouser/google-spreadsheet/node_modules/xml2js/lib/xml2js.js:7:59)
    at Request._callback (/Users/hellouser/google-spreadsheet/node_modules/google-spreadsheet/index.js:164:24)
    at Request.self.callback (/Users/hellouser/google-spreadsheet/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/hellouser/google-spreadsheet/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/hellouser/google-spreadsheet/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by bitliner** [comment]
Funny thing: if I start the program using `devtool` instead of `node`, there is no error and every thing works fine.

**Comment by theoephraim** [comment]
hm, what version of node were you using?

**Comment by theoephraim** [comment]
I've just a published a new version of this module which is a complete rewrite using Google's V4 Sheets API (v3 is being deprecated on March 3, 2020). **YOU MUST MIGRATE IF YOU ARE STILL USING THIS PACKAGE!**

**Docs available here - https://theoephraim.github.io/node-google-spreadsheet**

I do believe this issue should be fixed in the new version.
Please test it out and if you find that there is still a problem, reopen the issue.

Thanks! 😄
