### ISSUE TITLE
TypeError: Cannot read property '$' of undefined when using sheet.del();

### ISSUE THREAD

**Issue by maciej-w** [theoephraim/node-google-spreadsheet#159]
I just run your example code on a sheet of mine, and it works fine, changing the values of the rows, then adds a sheet but looks like it fails on this line of code:
`sheet.del(); //async `

If above line is commented out, error doesn't appear.

```
sheet 1: Sheet1 990x26
Read 40 rows
Cell R1C1 = 1
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property '$' of undefined
    at self.updateValuesFromResponseData (C:\Users\user\Documents\Visual Studio 2017\Projects\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\google-spreadsheet\index.js:539:37)
    at C:\Users\user\Documents\Visual Studio 2017\Projects\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\google-spreadsheet\index.js:436:50
    at Array.forEach (native)
    at C:\Users\user\Documents\Visual Studio 2017\Projects\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\google-spreadsheet\index.js:435:55
    at C:\Users\user\Documents\Visual Studio 2017\Projects\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\google-spreadsheet\index.js:166:15
    at Parser.<anonymous> (C:\Users\user\Documents\Visual Studio 2017\Projects\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\xml2js\lib\xml2js.js:489:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (C:\Users\user\Documents\Visual Studio 2017\Projects\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\xml2js\lib\xml2js.js:447:26)
    at emit (C:\Users\user\Documents\Visual Studio 2017\Projects\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\sax\lib\sax.js:624:35)
```

**Comment by theoephraim** [comment]
try
```
sheet.del(function(err) {
  if (err) console.log(err);
  else console.log('deleted!');
});
```
and you should be able to see what is happening.
Those `//async` notes in the readme are just to keep the example code shorter. They really should be called with a callback.

**Comment by andrewkmin** [comment]
The errors all seem to be undefined...
```sheet.bulkUpdateCells(cells, function(err){
        console.log('error!', err)
      }); //async ```
yields ```error! undefined
events.js:182
      throw er; // Unhandled 'error' event```

**Comment by maciej-w** [comment]
@theoephraim - sorry for late reply and thanks for help and writing great software!
