### ISSUE TITLE
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters

### ISSUE THREAD

**Issue by akylkb** [theoephraim/node-google-spreadsheet#274]
index.js
```javascript
const { GoogleSpreadsheet } = require('google-spreadsheet')
const creds = require('./client_secret.json')
async function accessSpreadsheet () {
  const doc = new GoogleSpreadsheet('ID123213213123123123213')
  await doc.useServiceAccountAuth(creds)
  await doc.loadInfo()
  const sheet = doc.sheetsByIndex[0]
  await sheet.addRow({ name: 'Larry Page', email: 'larry@google.com' })
}
accessSpreadsheet()
```

Error:
```
(node:36546) UnhandledPromiseRejectionWarning: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:140:13)
    at Object.request (https.js:309:10)
    at RedirectableRequest._performRequest (/Users/akyl/sheet-demo/node_modules/follow-redirects/index.js:169:24)
    at new RedirectableRequest (/Users/akyl/sheet-demo/node_modules/follow-redirects/index.js:66:8)
    at Object.wrappedProtocol.request (/Users/akyl/sheet-demo/node_modules/follow-redirects/index.js:307:14)
    at dispatchHttpRequest (/Users/akyl/sheet-demo/node_modules/axios/lib/adapters/http.js:179:25)
    at new Promise (<anonymous>)
    at httpAdapter (/Users/akyl/sheet-demo/node_modules/axios/lib/adapters/http.js:21:10)
    at dispatchRequest (/Users/akyl/sheet-demo/node_modules/axios/lib/core/dispatchRequest.js:52:10)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:36546) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:36546) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by theoephraim** [comment]
I think maybe there is something up with a weird document ID, that I had not encountered in my testing. Can you share the document ID with me? (you can email to `theozero@gmail.com` if you prefer)

**Comment by akylkb** [comment]
@theoephraim, Opened you access

**Comment by theoephraim** [comment]
Thanks for sharing it!

Ok I so I fixed the encoding issue, will deploy that and publish to npm shortly. You'll need to run `npm i google-spreadsheet@latest --save` - verify you get version 3.0.3

But I see another issue which is that it is inserting rows strangely - shifted over many columns rather than starting at the first column. I've been trying to figure it out and it looks like it may have something to do with some data validation rules. When I delete all those dropdowns you have in empty rows near the top of the sheet, it all works as expected. This makes me think it's something with how google is handling it and unfortunately not within my control. Maybe I'll throw a warning or something though when that happens
