### ISSUE TITLE
Unescaped characters

### ISSUE THREAD

**Issue by ogomez92** [theoephraim/node-google-spreadsheet#283]
Hi I'm running into a very weird issue, I cannot add a row to a sheet because it says something about unescaped characters, here is the log and the object

Microsoft Windows [Version 10.0.17763.973]
(c) 2018 Microsoft Corporation. All rights reserved.

google sheeting13
title changed
(the object htat falis is this one)
{
  'Start date of automated monitoring ': 'Wed Feb 05 2020 10:01:55 GMT+0100 (Central European Standard Time)',
  'Monitoring frequency in minutes': '0 minutes (0 hours)',
  'Automated check date': 'Wed Feb 05 2020 10:01:58 GMT+0100 (Central European Standard Time)',
  Data: 'div.contentarea',
  URL: 'MASKED',
  Changed: 'yes',
  Failed: 'no',
  'Note for Failure': ' ',
  Provenance: ' ',
  'False Positives times that the automated checking did not reflect any real update over the total number of checks': ' ',
  'False Negatives times that the automated checking missed a real update over the total number of checks': ' ',
  'Frequency the source link is not available errors': ' ',
  'Total number checks performed': ' ',
  Notes: ' '
}
Google Sheets error: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:139:13)
    at Object.request (https.js:309:10)
    at RedirectableRequest._performRequest (C:\Users\gomezsentiso\git\lists-monitor\node_modules\follow-redirects\index.js:169:24)
    at new RedirectableRequest (C:\Users\gomezsentiso\git\lists-monitor\node_modules\follow-redirects\index.js:66:8)
    at Object.wrappedProtocol.request (C:\Users\gomezsentiso\git\lists-monitor\node_modules\follow-redirects\index.js:307:14)
    at dispatchHttpRequest (C:\Users\gomezsentiso\git\lists-monitor\node_modules\axios\lib\adapters\http.js:179:25)
    at new Promise (<anonymous>)
    at httpAdapter (C:\Users\gomezsentiso\git\lists-monitor\node_modules\axios\lib\adapters\http.js:21:10)
    at dispatchRequest (C:\Users\gomezsentiso\git\lists-monitor\node_modules\axios\lib\core\dispatchRequest.js:52:10)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by theoephraim** [comment]
I believe I fixed this issue yesterday. Pull the latest version from npm and let me know if you're still seeing it. `npm i google-spreadsheet@latest --save`

**Comment by RoyDeng** [comment]
I get the same problem in 3.0.4 today.

**Comment by theoephraim** [comment]
@RoyDeng can you share the sheet with me? theozero@gmail.com
I did encounter this before and fix it, so I'm wondering what's going on.
You can see the test I added here: https://github.com/theoephraim/node-google-spreadsheet/blob/master/test/rows.test.js#L205

**Comment by theoephraim** [comment]
fixed - found a couple more spots that needed the encoding for the URL
