### ISSUE TITLE
saveCells with unchanged cell throws 400 bad request error

### ISSUE THREAD

**Issue by CherryDT** [theoephraim/node-google-spreadsheet#308]
This happens when calling `saveCells` with an unchanged/already-saved cell in the array:

```
Error: Google API error - [400] Invalid requests[0].updateCells: At least one field must be listed in 'fields'. (Use '*' to indicate all fields.)
    at createError (/mnt/c/Users/david/proj/google-spreadsheet-v2v3-wrapper/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/mnt/c/Users/david/proj/google-spreadsheet-v2v3-wrapper/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/mnt/c/Users/david/proj/google-spreadsheet-v2v3-wrapper/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:214:15)
    at IncomingMessage.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    url: ':batchUpdate',
    method: 'post',
    data: `{"requests":[{"updateCells":{"rows":[{"values":[{}]}],"fields":"","start":{"sheetId":603529019,"rowIndex":2,"columnIndex":0}}},{"updateCells":{"rows":[{"values":[{}]}],"fields":"","start":{"sheetId":603529019,"rowIndex":2,"columnIndex":1}}}],"includeSpreadsheetInResponse":true,"responseIncludeGridData":true,"responseRanges":["'Test 1'!A3","'Test 1'!B3"]}`,
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json;charset=utf-8',
      Authorization: 'Bearer XXXXXXXXX',
      'User-Agent': 'axios/0.19.2',
      'Content-Length': 356
    },
    baseURL: 'https://sheets.googleapis.com/v4/spreadsheets/1H7xxxxxxxxxx',

...
```

**Comment by theoephraim** [comment]
Do you have a larger code sample of what you're trying to do?

**Comment by CherryDT** [comment]
It should be as simple as this to reproduce:

```javascript
await sheet.loadCells('A1')
const cell = sheet.getCell(0, 0)
await sheet.saveCells([cell]) // fails
```

If `cell.value = 123` is before the save, it doesn't fail.
I'd expect it to just do nothing if the cell wasn't changed.

**Comment by theoephraim** [comment]
Ah got it. All my code and the tests are using on `saveUpdatedCells` which filters out unchanged cells and then calls `saveCells`. Generally this is the easier way to do things.
But regardless this shouldn't break. I'll take a look and try to get a fix in.

**Comment by theoephraim** [comment]
fixed in the latest version. Thanks for the report!
