### ISSUE TITLE
TypeError: Cannot read property 'worksheets' of undefined

### ISSUE THREAD

**Issue by DerEchteMauriice** [theoephraim/node-google-spreadsheet#359]
Errorcode:
TypeError: Cannot read property 'worksheets' of undefined
    at doc.getInfo (/home/Server/server.js:374:18)
    at /home/Server/node_modules/google-spreadsheet/index.js:182:25
    at Request._callback (/home/Server/node_modules/google-spreadsheet/index.js:157:20)
    at Request.self.callback (/home/Server/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/Server/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/Server/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)

Need Help pls..

**Comment by hochmanjoel** [comment]
Need more information (i.e. code snippets and environment)

**Comment by theoephraim** [comment]
Feel free to reopen with more code!
