### ISSUE TITLE
Request failed error 404

### ISSUE THREAD

**Issue by Romans96** [theoephraim/node-google-spreadsheet#386]
Hello! I'm trying to use authernticating wtih a service account.

Then trying on the sheet (where i have the email on the  share), when i try to use something like `await doc.loadInfo();`  it returns this error:

```
(node:12748) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (D:\Programmazione\Google API\test-google-sheet\node_modules\google-spreadsheet\node_modules\axios\lib\core\createError.js:16:15)
    at settle (D:\Programmazione\Google API\test-google-sheet\node_modules\google-spreadsheet\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (D:\Programmazione\Google API\test-google-sheet\node_modules\google-spreadsheet\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by theoephraim** [comment]
Looks to me like your document ID might be incorrect.
