### ISSUE TITLE
google-spreadsheet.js (npm) is not working when following the github example

### ISSUE THREAD

**Issue by yiouyou** [theoephraim/node-google-spreadsheet#392]
When following the basic exmaple code from https://github.com/theoephraim/node-google-spreadsheet, it's not working.

for example:
```
const { GoogleSpreadsheet } = require('google-spreadsheet')
const creds = require('./gsheet-creds.json')

const doc = new GoogleSpreadsheet('1nkNX-HfxYY5qs_MwXTiFQIxEajibJlTTUPeOHCX7ZVc')

doc.useServiceAccountAuth({
    client_email: creds.client_email,
    private_key: creds.private_key,
})

await doc.loadInfo()
console.log(doc.title)
```

it shows error:
```
sz@air:/mnt/d/coding/wxBot-dorm-seller/googlesheet$ node gsheet-google-spreadsheet.js
/mnt/d/coding/wxBot-dorm-seller/googlesheet/gsheet-google-spreadsheet.js:34
await doc.loadInfo()
^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

If remove the 'await' before doc.loadInfo(), it shows error:
```
sz@air:/mnt/d/coding/wxBot-dorm-seller/googlesheet$ node gsheet-google-spreadsheet.js
gsheet@gsheet-yiouyou.iam.gserviceaccount.com
/mnt/d/coding/wxBot-dorm-seller/googlesheet/node_modules/_google-spreadsheet@3.0.13@google-spreadsheet/lib/GoogleSpreadsheet.js:175
    if (!this._rawProperties) throw new Error('You must call `sheet.loadInfo()` before accessing this property');
                              ^

Error: You must call `sheet.loadInfo()` before accessing this property
    at GoogleSpreadsheet._ensureInfoLoaded (/mnt/d/coding/wxBot-dorm-seller/googlesheet/node_modules/_google-spreadsheet@3.0.13@google-spreadsheet/lib/GoogleSpreadsheet.js:175:37)
    at GoogleSpreadsheet._getProp (/mnt/d/coding/wxBot-dorm-seller/googlesheet/node_modules/_google-spreadsheet@3.0.13@google-spreadsheet/lib/GoogleSpreadsheet.js:192:10)
    at GoogleSpreadsheet.get title [as title] (/mnt/d/coding/wxBot-dorm-seller/googlesheet/node_modules/_google-spreadsheet@3.0.13@google-spreadsheet/lib/GoogleSpreadsheet.js:199:29)
    at Object.<anonymous> (/mnt/d/coding/wxBot-dorm-seller/googlesheet/gsheet-google-spreadsheet.js:35:17)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

I've tried many things and checked many examples from website and youtube. None of them is working for the latest google-spreadsheet. I haven't try anything older.

Appreciate any help here. Really want to get the google-spreadsheet.js working.

**Comment by VariXx** [comment]
The `await doc.loadInfo()` in your example needs to run inside of an [async function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function).

```
const { GoogleSpreadsheet } = require('google-spreadsheet');
const creds = require('./gsheet-creds.json')

const doc = new GoogleSpreadsheet('1nkNX-HfxYY5qs_MwXTiFQIxEajibJlTTUPeOHCX7ZVc')

async function test() {
    doc.useServiceAccountAuth({
        client_email: creds.client_email,
        private_key: creds.private_key,
    })    
    await doc.loadInfo()
    console.log(doc.title)
}

test()

```

You can also wrap it in an async [arrow function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) which is useful for testing. 

```
const { GoogleSpreadsheet } = require('google-spreadsheet');
const creds = require('./gsheet-creds.json')

const doc = new GoogleSpreadsheet('1nkNX-HfxYY5qs_MwXTiFQIxEajibJlTTUPeOHCX7ZVc')

(async() => {
    doc.useServiceAccountAuth({
        client_email: creds.client_email,
        private_key: creds.private_key,
    })    
    await doc.loadInfo()
    console.log(doc.title)
})()

```

**Comment by ChannelJuanNews** [comment]
did that and it still does not work for me... why would he include an example that doesn't work?

**Comment by theoephraim** [comment]
As others have mentioned, you can't call await at the top level for most versions of node.js
I wrote the examples this way to keep them shorter, thinking that this is known to most JS devs. But I've added a note now in the readme to hopefully make it clearer for any folks that are newer to JS.

If you're still having trouble, let me know and I can help you get it working.
