### ISSUE TITLE
UnhandledPromiseRejectionWarning: Duplicate header detected when using getRows() 

### ISSUE THREAD

**Issue by Scanerrr** [theoephraim/node-google-spreadsheet#394]
Hello

Playing around with this package and got an issue when trying to get list of rows

### CODE:

```
const { GoogleSpreadsheet } = require("google-spreadsheet");
const creds = require("../cred.json"); // the file saved above

(async () => {
  const doc = new GoogleSpreadsheet(
    "1rVqAjm-l_Urjd3TNmIc3SmTmz_OlgSoBuhY7RPgiuRg"
  );
  await doc.useServiceAccountAuth(creds);

  await doc.loadInfo();

  const sheet = doc.sheetsById[0]; 
  await sheet.getRows();
})();
```

### ERROR

```
(node:4490) UnhandledPromiseRejectionWarning: Error: Duplicate header detected: "Video length". Please make sure all non-empty headers are unique
    at /test/node_modules/google-spreadsheet/lib/GoogleSpreadsheetWorksheet.js:14:13
    at /test/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/test/node_modules/lodash/lodash.js:2990:24)
    at /test/node_modules/lodash/lodash.js:4894:18
    at Function.forEach (/test/node_modules/lodash/lodash.js:9368:14)
    at checkForDuplicateHeaders (/test/node_modules/google-spreadsheet/lib/GoogleSpreadsheetWorksheet.js:11:5)
    at GoogleSpreadsheetWorksheet.loadHeaderRow (/test/node_modules/google-spreadsheet/lib/GoogleSpreadsheetWorksheet.js:298:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleSpreadsheetWorksheet.getRows (/test/node_modules/google-spreadsheet/lib/GoogleSpreadsheetWorksheet.js:424:29)
    at async /test/src/index.js:14:3
(node:4490) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4490) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Lib version:
 "google-spreadsheet": "^3.0.13"

**Comment by theoephraim** [comment]
Can you confirm that you don't have 2 header cells with the same value in it? (ie 2 cells say "Video length")

Each header cell must be unique in order to use the row-based functions.

**Comment by ivoneijr** [comment]
Is there any way to call the getRows function for a specific range? 
So, this way I could leave out the duplicated header cell..
