### ISSUE TITLE
"Error: options.uri is a required argument" when trying to use setValue

### ISSUE THREAD

**Issue by josmcg** [theoephraim/node-google-spreadsheet#44]
```
var write_sheet = function(col , row , value){
        //convert col and row to single array value
        var sheet_row_length = sheet_info.worksheets[0].colCount;
        var row_value = (row - 1) * sheet_row_length;
        var index = row_value + col;
        spreadsheet.getCells(1, function(err , cell_array){
            cell_array[index].setValue(value, function(err){
                if(err){
                    console.log(err);
                    console.trace();
                }else{
                    console.log("success!");
                }
            })
        });
    };
```
Is the code I'm using when getting this. The stack trace is as follows
```
at /Users/joshmcgrath/Documents/Git/spellingbee/app.js:94:29
    at Request._callback (/Users/joshmcgrath/Documents/Git/spellingbee/node_modules/google-spreadsheet/index.js:129:20)
    at self.callback (/Users/joshmcgrath/Documents/Git/spellingbee/node_modules/google-spreadsheet/node_modules/request/request.js:123:22)
    at Request.emit (events.js:95:17)
    at Request.init (/Users/joshmcgrath/Documents/Git/spellingbee/node_modules/google-spreadsheet/node_modules/request/request.js:137:17)
    at new Request (/Users/joshmcgrath/Documents/Git/spellingbee/node_modules/google-spreadsheet/node_modules/request/request.js:99:8)
    at request (/Users/joshmcgrath/Documents/Git/spellingbee/node_modules/google-spreadsheet/node_modules/request/index.js:54:11)
    at async.series.request (/Users/joshmcgrath/Documents/Git/spellingbee/node_modules/google-spreadsheet/index.js:122:9)
    at /Users/joshmcgrath/Documents/Git/spellingbee/node_modules/google-spreadsheet/node_modules/async/lib/async.js:735:13
    at iterate (/Users/joshmcgrath/Documents/Git/spellingbee/node_modules/google-spreadsheet/node_modules/async/lib/async.js:253:13)
```
Willing to help if you can point me in the right direction.

**Comment by leroyoost** [comment]
Did you find a solution for this? I'm having the same problem with an extremely simple use case where I just set a value and then .save(callback). Any ideas?

**Comment by gtorodelvalle** [comment]
Hi @josmcg , I think we moved to https://github.com/theoephraim/node-google-spreadsheet/issues/90 ;)
