### ISSUE TITLE
loadCells functionality is not working

### ISSUE THREAD

**Issue by abidali7** [theoephraim/node-google-spreadsheet#509]
I have been trying to access cells values with all possible combination of loadCells as mentioned in: https://theoephraim.github.io/node-google-spreadsheet/#/classes/google-spreadsheet-worksheet?id=fn-loadcells

But none of them works & in return either we are getting error as `undefined` or the following one (see it's stacktraces): 
`TypeError: Cannot read property 'length' of undefined
    at /Users/abidali/Files/Repositories/project/node_modules/google-spreadsheet/lib/GoogleSpreadsheetWorksheet.js:62:47
    at arrayEach (/Users/abidali/Files/Repositories/project/node_modules/google-spreadsheet/node_modules/lodash/lodash.js:530:11)
    at Function.forEach (/Users/abidali/Files/Repositories/project/node_modules/google-spreadsheet/node_modules/lodash/lodash.js:9410:14)
    at GoogleSpreadsheetWorksheet._fillCellData (/Users/abidali/Files/Repositories/project/node_modules/google-spreadsheet/lib/GoogleSpreadsheetWorksheet.js:58:7)
    at GoogleSpreadsheet._updateOrCreateSheet (/Users/abidali/Files/Repositories/project/node_modules/google-spreadsheet/lib/GoogleSpreadsheet.js:212:32)
    at /Users/abidali/Files/Repositories/project/node_modules/google-spreadsheet/lib/GoogleSpreadsheet.js:382:38
    at arrayEach (/Users/abidali/Files/Repositories/project/node_modules/google-spreadsheet/node_modules/lodash/lodash.js:530:11)
    at Function.forEach (/Users/abidali/Files/Repositories/project/node_modules/google-spreadsheet/node_modules/lodash/lodash.js:9410:14)
    at GoogleSpreadsheet.loadCells (/Users/abidali/Files/Repositories/project/node_modules/google-spreadsheet/lib/GoogleSpreadsheet.js:382:7)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm ERR! Test failed.  See above for more details.
`

**Comment by BoKKeR** [comment]
It works for me with: 
```
import {
  GoogleSpreadsheet,
  GoogleSpreadsheetWorksheet,
} from "google-spreadsheet";

let sheet: GoogleSpreadsheetWorksheet;
await sheet.loadCells("A1:AL2000");
  const doc = new GoogleSpreadsheet(docKey as string);
  console.log("Loading document");

  await doc.useServiceAccountAuth({
    client_email: service_account.client_email,
    private_key: service_account.private_key,
  });

  await doc.loadInfo();

  sheet = doc.sheetsByIndex[0];
  await sheet.loadCells("A1:AL2000");
```

**Comment by theoephraim** [comment]
can you provide a code sample or some more info?
It definitely works for lots of people and in the tests, so it must be something specific to your usage or your document.

**Comment by theoephraim** [comment]
Going to close this for now. Please reopen with some more details if it's still a problem.
