### ISSUE TITLE
Google API error - [503] The service is currently unavailable.

### ISSUE THREAD

**Issue by cthomaschase** [theoephraim/node-google-spreadsheet#512]
Hi,

I've been getting these errors lately, however, the data looks to be successfully inserted into the sheet.

Has anyone else seen this?

**Comment by theoephraim** [comment]
Is it consistent with a specific sheet? Or just intermittent on a variety of docs?
I have encountered some unexpected errors in the past that were related to some weird data in a sheet, but if its just intermittent, I would assume it's just google's API being wonky.

**Comment by theoephraim** [comment]
Going to close this. Please reopen with some more details if it's still happening.

**Comment by puremana** [comment]
I keep getting the same error, but I might not be handling errors properly. It is only happening on rare occasions

```
/home/ubuntu/vail-discord-bot/node_modules/google-spreadsheet/node_modules/axios/lib/core/createError.js:16
  var error = new Error(message);
              ^

Error: Google API error - [503] The service is currently unavailable.
    at createError (/home/ubuntu/vail-discord-bot/node_modules/google-spreadsheet/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/ubuntu/vail-discord-bot/node_modules/google-spreadsheet/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/ubuntu/vail-discord-bot/node_modules/google-spreadsheet/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
```

**Comment by theoephraim** [comment]
@puremana - if it's intermittent and not happening consistently when using a specific doc/sheet, then I assume it's just google's service itself having errors for no reason...
