### ISSUE TITLE
loadCells fail if ColumnStart and EndIndex are same

### ISSUE THREAD

**Issue by deepakaggarwal7** [theoephraim/node-google-spreadsheet#517]
I want to load a column from a sheet. Following code fails with  
**TypeError: Cannot read property 'length' of undefined**

` await masterSheet.loadCells({startRowIndex:1, endRowIndex:100, startColumnIndex:21, endColumnIndex:21})`

If I use a bigger number for endColumnIndex, it works.

Version: `"google-spreadsheet": "^3.1.15",`
 

Detailed Error:

      at node_modules/google-spreadsheet/lib/GoogleSpreadsheetWorksheet.js:62:47
      at arrayEach (node_modules/lodash/lodash.js:530:11)
      at Function.forEach (node_modules/lodash/lodash.js:9410:14)
      at GoogleSpreadsheetWorksheet._fillCellData (node_modules/google-spreadsheet/lib/GoogleSpreadsheetWorksheet.js:58:7)
      at GoogleSpreadsheet._updateOrCreateSheet (node_modules/google-spreadsheet/lib/GoogleSpreadsheet.js:212:32)
      at node_modules/google-spreadsheet/lib/GoogleSpreadsheet.js:382:38
      at arrayEach (node_modules/lodash/lodash.js:530:11)
      at Function.forEach (node_modules/lodash/lodash.js:9410:14)
      at GoogleSpreadsheet.loadCells (node_modules/google-spreadsheet/lib/GoogleSpreadsheet.js:382:7)

**Comment by theoephraim** [comment]
These params are being passed through to google's API and that is how it works - see https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/other#GridRange
