### ISSUE TITLE
Suddenly encountering "Error: 3 INVALID_ARGUMENT: Invalid BatchCreateSessions request." When calling loadInfo()

### ISSUE THREAD

**Issue by JacobStenson1** [theoephraim/node-google-spreadsheet#570]
Hi there.

I'm suddenly encountering an error where when attempting to call the `loadInfo` function on my `doc` variable, see below:
```
const doc = new GoogleSpreadsheet(
  '<GOOGLE_SHEET_ID>'
);
await doc.useServiceAccountAuth(serviceAcc);
await doc.loadInfo();
```
When calling `await doc.loadInfo();` I am met with the following error:

```
E:\GitHub\dpd\international-apis\services\apis\node_modules\google-gax\node_modules\@grpc\grpc-js\src\call.ts:81
  return Object.assign(new Error(message), status);
                       ^
Error: 3 INVALID_ARGUMENT: Invalid BatchCreateSessions request.
    at Object.callErrorFromStatus (E:\GitHub\dpd\international-apis\services\apis\node_modules\google-gax\node_modules\@grpc\grpc-js\src\call.ts:81:24)
    at Object.onReceiveStatus (E:\GitHub\dpd\international-apis\services\apis\node_modules\google-gax\node_modules\@grpc\grpc-js\src\client.ts:343:36)
    at E:\GitHub\dpd\international-apis\services\apis\node_modules\google-gax\node_modules\@grpc\grpc-js\src\call-stream.ts:206:27
    at Object.onReceiveStatus (E:\GitHub\dpd\international-apis\services\apis\node_modules\grpc-gcp\src\index.ts:129:15)
    at InterceptingListenerImpl.onReceiveStatus (E:\GitHub\dpd\international-apis\services\apis\node_modules\google-gax\node_modules\@grpc\grpc-js\src\call-stream.ts:202:19)
    at Object.onReceiveStatus (E:\GitHub\dpd\international-apis\services\apis\node_modules\google-gax\node_modules\@grpc\grpc-js\src\client-interceptors.ts:462:34)
    at Object.onReceiveStatus (E:\GitHub\dpd\international-apis\services\apis\node_modules\google-gax\node_modules\@grpc\grpc-js\src\client-interceptors.ts:424:48)
    at E:\GitHub\dpd\international-apis\services\apis\node_modules\google-gax\node_modules\@grpc\grpc-js\src\call-stream.ts:330:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 3,
  details: 'Invalid BatchCreateSessions request.',
  metadata: Metadata {
    internalRepr: Map(3) {
      'grpc-server-stats-bin' => [Array],
      'google.rpc.badrequest-bin' => [Array],
      'grpc-status-details-bin' => [Array]
    },
    options: {}
  },
  note: 'Exception occurred in retry method that was not classified as transient'
}
```

I was wondering if anyone else had been encountering this issue and if they'd found a solution?

**Comment by JacobStenson1** [comment]
This has been fixed. The issue was to do with how I ran the shell script in my `package.json` which ran the above.
I dont believe the issue was related to this package.
