### ISSUE TITLE
Cannot create a string longer than 0x1fffffe8 characters

### ISSUE THREAD

**Issue by Jabali-tier** [theoephraim/node-google-spreadsheet#579]
After updating Node version to 14 and above,

When calling `sheet.loadCells()` I receive:

```
buffer.js:821
    return this.utf8Slice(start, end);
                ^

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Buffer.toString (buffer.js:821:17)
    at IncomingMessage.handleStreamEnd (/Users/asd/node_modules/google-spreadsheet/node_modules/axios/lib/adapters/http.js:262:41)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ERR_STRING_TOO_LONG'
}
```

The spread sheet has 12100 entries with 15 column - one having a background color - which used to be working fine on older Node versions

**Comment by DustinJSilk** [comment]
Im getting the same at about 14k rows X 2 columns. Looks like a limitation with node

**Comment by theoephraim** [comment]
Perhaps you could load the cells in several batches?

Closing for now as this seems like an underlying issue with node itself.
