### ISSUE TITLE
Not working on Deno

### ISSUE THREAD

**Issue by pickaxe828** [theoephraim/node-google-spreadsheet#597]
Code:
```ts
import { GoogleSpreadsheet } from "npm:google-spreadsheet"

const creds = JSON.parse(Deno.readTextFileSync("./cred.json"))

// Initialize the sheet - doc ID is the long id in the sheets URL
const fr = new GoogleSpreadsheet("")
const to = new GoogleSpreadsheet("")

await fr.useServiceAccountAuth(creds)
await to.useServiceAccountAuth(creds)
```
Error:
```ts
error: Uncaught Error: Not implemented: crypto.Sign
  throw new Error(message);
        ^
    at notImplemented (https://deno.land/std@0.168.0/node/_utils.ts:23:9)
    at new Sign (https://deno.land/std@0.168.0/node/internal/crypto/sig.ts:45:5)
    at Object.createSign (https://deno.land/std@0.168.0/node/crypto.ts:268:10)
    at Object.sign (file:///C:/Users/user/AppData/Local/deno/npm/registry.npmjs.org/jwa/2.0.0/index.js:151:25)
    at Object.jwsSign [as sign] (file:///C:/Users/user/AppData/Local/deno/npm/registry.npmjs.org/jws/4.0.0/lib/sign-stream.js:32:24)
    at GoogleToken.requestToken (file:///C:/Users/user/AppData/Local/deno/npm/registry.npmjs.org/gtoken/5.3.2/build/src/index.js:225:31)
    at GoogleToken.getTokenAsyncInner (file:///C:/Users/user/AppData/Local/deno/npm/registry.npmjs.org/gtoken/5.3.2/build/src/index.js:163:21)
    at GoogleToken.getTokenAsync (file:///C:/Users/user/AppData/Local/deno/npm/registry.npmjs.org/gtoken/5.3.2/build/src/index.js:142:55)
    at GoogleToken.getToken (file:///C:/Users/user/AppData/Local/deno/npm/registry.npmjs.org/gtoken/5.3.2/build/src/index.js:94:21)
    at JWT.refreshTokenNoCache (file:///C:/Users/user/AppData/Local/deno/npm/registry.npmjs.org/google-auth-library/6.1.6/build/src/auth/jwtclient.js:158:36)
```
`./cred.json` is downloaded straight from Google and works fine in Node. (Code is pretty much the same)

**Comment by nopeless** [comment]
Unless author explicitly mentions deno support, do not expect it to work on deno. Deno is not supposed to be a drop-in replacement for node

If you want Deno to be supported, change the title

**Comment by theoephraim** [comment]
please give the latest release a try. Not promising anything, but google-auth-library is now an optional peer dependency, so you can probably get it working. Although you'll need to handle auth yourself...
