### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'backgroundColor')

### ISSUE THREAD

**Issue by absemetov** [theoephraim/node-google-spreadsheet#598]
Hello!
In my code when backgroundColor red I delete produc from shop.
I have problem when I reset backgroundColor cell. I cant read backgroundColor property.
````
const ID = sheet.getCell(j, 1);
const prodMustDel = ID.backgroundColor && Object.keys(ID.backgroundColor).length === 1 && ID.backgroundColor.red === 1
````
After comment freeze the object, code work
````
_getFormatParam(param) {
    // we freeze the object so users don't change nested props accidentally
    // TODO: figure out something that would throw an error if you try to update it?
    if (_.get(this._draftData, `userEnteredFormat.${param}`)) {
      throw new Error('User format is unsaved - save the cell to be able to read it again');
    }
    // return Object.freeze(this._rawData.userEnteredFormat[param]);
  }
````
Error output
```
TypeError: Cannot read properties of undefined (reading 'backgroundColor')
>      at GoogleSpreadsheetCell._getFormatParam (/home/ubuntu/rzk-com-ua/functions/node_modules/google-spreadsheet/lib/GoogleSpreadsheetCell.js:111:57)
>      at GoogleSpreadsheetCell.get backgroundColor [as backgroundColor] (/home/ubuntu/rzk-com-ua/functions/node_modules/google-spreadsheet/lib/GoogleSpreadsheetCell.js:125:39)
```

**Comment by absemetov** [comment]
Strange behavior, maybe the problem was in the low speed of the Internet.
