### ISSUE TITLE
When I call this function, I'm getting this error C:\Users\user\Desktop\wpbott\node_modules\google-spreadsheet\lib\GoogleSpreadsheetWorksheet.js:408     const rows = await this.addRows([rowValues], options);                             ^  TypeError: Cannot read properties of undefined (reading 'addRows')     at addRow (C:\Users\user\Desktop\wpbott\node_modules\google-spreadsheet\lib\GoogleSpreadsheetWorksheet.js:408:29)     at node:internal/util:364:7     at new Promise (<anonymous>)     at addRow (node:internal/util:350:12)     at accessSpreadsheet (C:\Users\user\Desktop\wpbott\index1.js:36:38)     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### ISSUE THREAD

**Issue by pmdnawaz1** [theoephraim/node-google-spreadsheet#609]
```
const addDataToSheet = async (sheetId, data) => {

   const doc = new GoogleSpreadsheet(sheetId);
//When I'm doing console.log(data) here, I can see my object data
   async function accessSpreadsheet() {
      await doc.useServiceAccountAuth({
        client_email: creds.client_email,
        private_key: creds.private_key,
      });
      await doc.loadInfo(); 
      const sheet = doc.sheetsByIndex[0];
      console.log(doc.title); 
      console.log(sheet.title);
      console.log(sheet.rowCount);
      const rowValues = Object.values(data);
      const addRow = promisify(sheet.addRow)
      await promisify(sheet.addRow)(rowValues);
   }
   accessSpreadsheet();
 };
```

I'm sending data and sheetId here

```
await addDataToSheet('1mbvrmGbwZBlPYaYSf-Ftoeoz9Jirhmeg1HmLre_KlQ4',
{
      Name: userData[from].Name,
      Age: userData[from].Age,
      Gender: userData[from].Gender
    });
```

**Comment by theoephraim** [comment]
- not sure why you are calling promisify on addRow
- you're also not awaiting the call to `accessSpreadsheet`, so any error there will be swallowed
- no need to create another function inside addDataToSheet
- you probably also dont want to re-initialize the auth / sheet every time...

anyway... try this:

```js
async function (sheetId, data) {
  const doc = new GoogleSpreadsheet(sheetId);
  await doc.useServiceAccountAuth({
    client_email: creds.client_email,
    private_key: creds.private_key,
  });
  await doc.loadInfo(); 
  const sheet = doc.sheetsByIndex[0];
  console.log(doc.title); 
  console.log(sheet.title);
  console.log(sheet.rowCount);
  const row = await sheet.addRow(data);
  return row;
}


await addDataToSheet('1mbvrmGbwZBlPYaYSf-Ftoeoz9Jirhmeg1HmLre_KlQ4', {
  Name: userData[from].Name,
  Age: userData[from].Age,
  Gender: userData[from].Gender
});
```
