### ISSUE TITLE
Lodash related error trying to use the latest version 4.0.1

### ISSUE THREAD

**Issue by igormartimiano** [theoephraim/node-google-spreadsheet#632]
Hey there!
Tried to execute a simple node script and got the following error:

```
.../dist-raw/node-internal-modules-esm-resolve.js:366
    throw new ERR_MODULE_NOT_FOUND(
          ^
CustomError: Cannot find module '.../node_modules/lodash/compact' imported from .../node_modules/google-spreadsheet/dist/index.mjs
    at finalizeResolution (.../node_modules/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366:11)
    at moduleResolve (.../node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
    at Object.defaultResolve (.../node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at .../node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (.../node_modules/ts-node/src/esm.ts:168:34)
    at .../node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (.../node_modules/ts-node/src/esm.ts:409:21)
    at resolve (.../node_modules/ts-node/src/esm.ts:197:12)
    at resolve (.../node_modules/ts-node/src/child/child-loader.ts:15:39)
    at nextResolve (node:internal/modules/esm/loader:164:28)
```

Tried to downgrade the version to 3.x and it worked. I believe it might be related to changes in the new version.
My package.json deps:

```
  "devDependencies": {
    "@apify/tsconfig": "^0.1.0",
    "@swc/core": "^1.3.62",
    "@types/node": "^20.2.5",
    "commitizen": "^4.3.0",
    "cz-conventional-changelog": "^3.3.0",
    "husky": "^8.0.3",
    "nodemon": "^2.0.22",
    "snazzy": "^9.0.0",
    "ts-node": "^10.9.1",
    "ts-standard": "^12.0.2",
    "typescript": "^5.1.3"
  },
  "dependencies": {
    "crawlee": "^3.3.3",
    "dotenv": "^16.1.4",
    "google-auth-library": "^8.8.0",
    "google-spreadsheet": "^4.0.1",
    "playwright": "*"
  },
```

My simple script:

```
import { GoogleSpreadsheet } from 'google-spreadsheet'
import { JWT } from 'google-auth-library'

const jwt = new JWT({...})
const doc = new GoogleSpreadsheet('my_sheet_id', jwt)

await doc.loadInfo()
await doc.updateProperties({ title: 'renamed doc' })
```

**Comment by theoephraim** [comment]
@igormartimiano - checking it out now!

**Comment by theoephraim** [comment]
@igormartimiano - please try v4.0.2. 

Apologies for the hassle!

**Comment by igormartimiano** [comment]
@theoephraim No worries! Worked like a charm, thank you.
