### ISSUE TITLE
HTTP error 403: Forbidden "If-Match or If-None-Match header or entry etag attribute required

### ISSUE THREAD

**Issue by slavafomin** [theoephraim/node-google-spreadsheet#78]
Hello!

I'm trying to change the value of the cell. However, when I run `cell.setValue(newValue)` I'm getting the following error:

```
Unhandled rejection Error: Error: HTTP error 403: Forbidden "If-Match or If-None-Match header or entry etag attribute required"
    at Request._callback (/app/node_modules/google-spreadsheet/index.js:135:20)
    at Request.self.callback (/app/node_modules/google-spreadsheet/node_modules/request/request.js:123:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/app/node_modules/google-spreadsheet/node_modules/request/request.js:877:14)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/app/node_modules/google-spreadsheet/node_modules/request/request.js:828:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickDomainCallback (node.js:429:17)
From previous event:
    at /app/api/services/TestService.js:438:25
From previous event:
    at /app/api/services/TestService.js:435:12
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.module.exports.testGoogleSpreadsheet (/app/api/services/TestService.js:430:8)
    at Object.bound [as testGoogleSpreadsheet] (/home/user/.nvm/versions/node/v5.5.0/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at repl:1:13
    at REPLServer.defaultEval (repl.js:254:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
    at ReadStream.onkeypress (readline.js:106:10)
    at emitTwo (events.js:100:13)
    at ReadStream.emit (events.js:185:7)
    at emitKeys (readline.js:1251:14)
    at next (native)
    at ReadStream.onData (readline.js:919:36)
    at emitOne (events.js:90:13)
    at ReadStream.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at ReadStream.Readable.push (_stream_readable.js:111:10)
    at TTY.onread (net.js:523:20)
```

What could be the reason for this?

Thank you!

**Comment by ctulek** [comment]
I have the same problem, too (So many reporting today : ) )

**Comment by rajbits** [comment]
+1 I have the same problem too. Any solutions yet?

**Comment by lauriejim** [comment]
Same for me

**Comment by lauriejim** [comment]
https://github.com/theoephraim/node-google-spreadsheet/pull/63
