### ISSUE TITLE
Error when trying to read some cells

### ISSUE THREAD

**Issue by buckett** [theoephraim/node-google-spreadsheet#82]
I was attempting to read some cells with 

    my_sheet.getCells(1, {"min-row": "1", "min-col": "1", "max-col": "1"}, cb);

and I am getting a strack trace:

```
22:29:25 web.1  | events.js:85
22:29:25 web.1  |       throw er; // Unhandled 'error' event
22:29:25 web.1  |             ^
22:29:25 web.1  | TypeError: Cannot read property 'substr' of undefined
22:29:25 web.1  |     at new SpreadsheetCell (/Users/buckett/Documents/sakai/sakai-cla-robot/node_modules/google-spreadsheet/index.js:422:36)
22:29:25 web.1  |     at /Users/buckett/Documents/sakai/sakai-cla-robot/node_modules/google-spreadsheet/index.js:292:21
22:29:25 web.1  |     at Array.forEach (native)
22:29:25 web.1  |     at /Users/buckett/Documents/sakai/sakai-cla-robot/node_modules/google-spreadsheet/index.js:291:15
22:29:25 web.1  |     at /Users/buckett/Documents/sakai/sakai-cla-robot/node_modules/google-spreadsheet/index.js:148:15
22:29:25 web.1  |     at Parser.<anonymous> (/Users/buckett/Documents/sakai/sakai-cla-robot/node_modules/xml2js/lib/xml2js.js:484:18)
22:29:25 web.1  |     at Parser.emit (events.js:107:17)
22:29:25 web.1  |     at Object.onclosetag (/Users/buckett/Documents/sakai/sakai-cla-robot/node_modules/xml2js/lib/xml2js.js:445:26)
22:29:25 web.1  |     at emit (/Users/buckett/Documents/sakai/sakai-cla-robot/node_modules/sax/lib/sax.js:639:35)
22:29:25 web.1  |     at emitNode (/Users/buckett/Documents/sakai/sakai-cla-robot/node_modules/sax/lib/sax.js:644:5)
22:29:25 web.1  | exited with code 1
```

Basically the inputValue on the cell is undefined.

**Comment by bradoyler** [comment]
@buckett Looks like @groupsky already created a PR to fix this issue. See: #87 

@theoephraim Can you look at merging #87 ?

**Comment by theoephraim** [comment]
Just released a big update! Please upgrade to the latest version and let me know if you are still having problems. Thanks :)

**Comment by amoshaviv** [comment]
still not working.... :(

**Comment by theoephraim** [comment]
@amoshaviv can you provide a new example?
In this new update, I removed `inputValue` and now you have access to `value`, `numericValue` and `formula`. I think its much clearer now.

**Comment by theoephraim** [comment]
Should be fixed!
